# Site settings
title: "{Codetail}"
email: codetail.io@github.io
description: We love to implement awesome things
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codetail.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  codetail

# Build settings
markdown: kramdown
highlighter: pygments


exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md